services:
  server:
    # Build a lightweight custom image that reuses the
    # official server image and overlays our built front.
    build:
      context: ../..
      dockerfile: packages/twenty-docker/twenty/Dockerfile.front-overlay
      args:
        REACT_APP_SERVER_BASE_URL: ${SERVER_URL}
    image: maninfini/twenty:maninfini

  worker:
    # Worker doesn't need the frontend; reuse the same
    # final image for consistency.
    image: maninfini/twenty:maninfini
