services:
  server:
    # Build a lightweight custom image from the official one
    # and patch the built index.html OG tags + logo.
    build:
      context: ../..
      dockerfile: packages/twenty-docker/twenty/Dockerfile.patch-html
    image: maninfini/twenty:maninfini

  worker:
    # Reuse the same patched image for consistency.
    image: maninfini/twenty:maninfini
